name: Backend CI

on:
  push:
    branches: [main]
    paths: ["server/**", ".github/workflows/backend.yml"]
  pull_request:
    branches: [main]
    paths: ["server/**", ".github/workflows/backend.yml"]

jobs:
  backend:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run tests
        env:
          MONGO_URI_TEST: mongodb://localhost:27017/testdb
        run: npm run test

      - name: Build project
        run: npm run build
